/* ============================================================
   FESTISALE — Bilingual System (HU / EN)
   Uses data-i18n attributes and localStorage for persistence.
   ============================================================ */

const I18N = {
  hu: {
    /* Nav */
    'nav.products': 'Termékek',
    'nav.standalone': 'Önálló terminálok',
    'nav.standalone_sub': 'NewLand S30 · N750 · N950S',
    'nav.kassza': 'Kassza rendszer',
    'nav.kassza_sub': 'Festisale + X800 · S90',
    'nav.pricing': 'Árak',
    'nav.contact': 'Kapcsolat',
    'nav.cta': 'Ajánlatkérés',

    /* Common */
    'cta.quote': 'Ajánlatkérés',
    'cta.products': 'Termékeink',
    'cta.learn_more': 'Részletek',
    'cta.demo': 'Bemutatót kérek',
    'cta.start': 'Indítsd el',

    /* Home — Hero */
    'home.tag': 'Magyar piacon elérhető — bankfüggetlen megoldás',
    'home.h1_a': 'Fizetés',
    'home.h1_b': 'egyszerűen.',
    'home.lead': 'Bankkártya-elfogadás modern NewLand terminálokkal — önállóan vagy teljes kassza rendszerként. Nincs havidíj, nincs bankváltás.',
    'home.meta.merchants': 'kereskedő',
    'home.meta.uptime': 'tranzakció uptime',
    'home.meta.activation': 'Élesítés',
    'home.meta.activation_val': '48h alatt',

    /* Stats marquee */
    'marquee.1': '400 000+ KKV Magyarországon',
    'marquee.2': '60%+ tranzakció már digitális',
    'marquee.3': '18%/év bankkártyás növekedés',
    'marquee.4': 'Bankfüggetlen megoldás',
    'marquee.5': 'NAV megfelelő kassza',
    'marquee.6': 'Magyar helyszíni support',

    /* Home — Paths */
    'paths.eyebrow': 'Két út, egy célhoz',
    'paths.title': 'Válaszd ki, ami az üzletedhez illik.',
    'paths.lead': 'Akár csak kártyaelfogadásra van szükséged, akár teljes pénztárrendszerre — mindkettőhöz prémium NewLand hardver és magyar support tartozik.',
    'paths.standalone_tag': 'Önálló terminálok',
    'paths.standalone_t': 'Csak kártyaelfogadás',
    'paths.standalone_p': 'Hordozható mini POS-tól a SmartPOS-ig — 3 NewLand modell, mind 0,65% jutalék, havidíj nélkül.',
    'paths.kassza_tag': 'Kassza rendszer',
    'paths.kassza_t': 'Festisale + hardver',
    'paths.kassza_p': 'NAV-megfelelő kassza szoftver, készletkezelés és integrált kártyaelfogadás. 25 000 Ft/hó + 0,35%.',

    /* Segments */
    'seg.eyebrow': 'Kinek szól',
    'seg.title': 'Bármilyen üzlet — minden méretben.',
    'seg.lead': 'A FESTIPAY rendszerét több mint 12 ágazatban használják. Néhány tipikus eset:',
    'seg.retail.t': 'Kiskereskedelem',
    'seg.retail.p': 'ABC, butik, szakbolt — gyors NFC fizetés a pult mellett.',
    'seg.retail.m': '120 000+ potenciális üzlet',
    'seg.hospo.t': 'Vendéglátás',
    'seg.hospo.p': 'Kávézó, étterem, bár — hordozható terminál minden asztalhoz.',
    'seg.hospo.m': '45 000+ vendéglátóhely',
    'seg.mobile.t': 'Mobil / stand',
    'seg.mobile.p': 'Piac, vásár, food truck — akku, 4G, kompakt méret.',
    'seg.mobile.m': '20 000+ mobil kereskedő',
    'seg.service.t': 'Szolgáltatás',
    'seg.service.p': 'Taxi, futár, kozmetika — egyszerű setup, NAV ready.',
    'seg.service.m': '60 000+ szolgáltató',

    /* Features grid */
    'feats.eyebrow': 'Miért FESTIPAY',
    'feats.title': 'Hat ok, amiért már 400 000+ KKV vált.',
    'feats.f1.t': 'Bankfüggetlen',
    'feats.f1.p': 'Nem kell bankot váltani — a meglévő számládhoz csatlakozik. Forgalmaid maradnak ahol szoktak.',
    'feats.f2.t': 'Nincs havidíj',
    'feats.f2.p': 'Csak forgalom után fizetsz: 0,65% tranzakciónként. Nincs setup díj, nincs hűségidő.',
    'feats.f3.t': 'NAV megfelelő',
    'feats.f3.p': 'A Festisale szoftver hivatalos NAV adóügyi kassza — automatikus napi zárás, online adatszolgáltatás.',
    'feats.f4.t': '48 órás élesítés',
    'feats.f4.p': 'Ajánlatkéréstől az első tranzakcióig 2 munkanap. Helyszíni betanítás, magyar nyelvű kézikönyv.',
    'feats.f5.t': 'Magyar support',
    'feats.f5.p': 'Telefon, e-mail, élő chat. Helyszíni szerviz Budapesten és 12 vidéki nagyvárosban.',
    'feats.f6.t': 'Modern hardver',
    'feats.f6.p': 'NewLand prémium terminálok — NFC, érintőképernyő, hosszú üzemidő, ipari szintű tartósság.',

    /* Testimonials */
    'testi.eyebrow': 'Mit mondanak rólunk',
    'testi.title': 'Magyar kereskedők, valós tapasztalatok.',
    'testi.1.q': 'Két hét alatt visszahozta a befektetést — a kávézó forgalmának 70%-a kártyás, és a havidíj-mentes konstrukció óriási előny.',
    'testi.1.n': 'K. Eszter',
    'testi.1.r': 'Sigil Café · Budapest VII.',
    'testi.2.q': 'A NAV-zárás magától megy, a betanítás 30 perc volt. A két kollégám is azonnal kezelte a Festisale-t.',
    'testi.2.n': 'N. Péter',
    'testi.2.r': 'Tulipán Pékség · Debrecen',
    'testi.3.q': 'A taxiban 24/7 használjuk az S30-at, és még egyszer sem hagyott cserben. Az NFC fizetés ~0.3 másodperc, az ügyfelek imádják.',
    'testi.3.n': 'V. Tamás',
    'testi.3.r': 'Mobiltaxi szolgáltatás',

    /* CTA */
    'finalcta.eyebrow': 'Készen állsz?',
    'finalcta.title': 'Indítsd el az üzleted kártyás bevételét — még a héten.',
    'finalcta.lead': 'Töltsd ki az ajánlatkérőt, vagy hívj minket: a csapatunk 1 munkanap alatt visszajelez egy testreszabott konstrukcióval.',
    'finalcta.btn_demo': 'Bemutatót kérek',
    'finalcta.btn_call': 'Hívás: +36 1 555 0100',

    /* Footer */
    'footer.tagline': 'Modern, bankfüggetlen kártyaelfogadás magyar kereskedőknek. Egy márka — két út: önálló terminál vagy teljes kassza rendszer.',
    'footer.products': 'Termékek',
    'footer.company': 'Cég',
    'footer.support': 'Support',
    'footer.about': 'Rólunk',
    'footer.partners': 'Partnerek',
    'footer.careers': 'Karrier',
    'footer.help': 'Súgóközpont',
    'footer.docs': 'Dokumentumok',
    'footer.status': 'Rendszerstátusz',
    'footer.privacy': 'Adatkezelés',
    'footer.terms': 'ÁSZF',
    'footer.copy': '© 2026 FESTIPAY Zrt. — Minden jog fenntartva.',

    /* Terminals page */
    'term.eyebrow': '01 — Önálló terminálok',
    'term.h1_a': 'Bankkártya-elfogadás',
    'term.h1_b': 'havidíj nélkül.',
    'term.lead': 'Három NewLand modell, egyetlen ajánlatban: 0,65% jutalék minden tranzakcióra, semmi rejtett költség.',

    'term.s30.tag': 'miniPOS · belépő',
    'term.s30.title': 'NewLand S30',
    'term.s30.sub': 'Slim. Smart. Sleek. A legkisebb és legkönnyebb terminálunk — 138 gramm, 16,5 mm vastag. Tökéletes, ha mobilitás kell, vagy a pult helye szűkös.',
    'term.s30.f1': 'NFC + Chip + Mágnessáv',
    'term.s30.f2': '0,3 mp fizetési idő',
    'term.s30.f3': 'PCI 7.x biztonság',
    'term.s30.f4': 'WiFi + 4G hálózat',

    'term.n750.tag': 'Android miniPOS',
    'term.n750.title': 'NewLand N750',
    'term.n750.sub': 'Compact. Connected. Confident. 5,5"-os érintőképernyő Androidon — saját alkalmazások futtatása, fejlett tranzakciós napló, hűségprogram-integráció.',
    'term.n750.f1': 'Android 12 OS',
    'term.n750.f2': '5,5" HD kijelző',
    'term.n750.f3': '4G + WiFi + BT',
    'term.n750.f4': 'App support',

    'term.n950s.tag': 'SmartPOS · prémium',
    'term.n950s.title': 'NewLand N950S',
    'term.n950s.sub': 'Premium. Powerful. Portable. Octa-core Android, 3500 mAh akku, magas fényerő. Ha napi 200+ tranzakciót vár, ez a csúcsmodell.',
    'term.n950s.f1': '3500 mAh akku',
    'term.n950s.f2': 'Octa-core CPU',
    'term.n950s.f3': '2300+ tranzakció / töltés',
    'term.n950s.f4': 'Ipari tartósság',

    'term.spec.hw': 'Hardver ár',
    'term.spec.fee': 'Tranzakciós díj',
    'term.spec.use': 'Ideális használat',
    'term.s30.use': 'Mobil, taxi, futár, food truck',
    'term.n750.use': 'Bolt, kávézó, recepció',
    'term.n950s.use': 'Étterem, prémium butik, magas forgalom',

    'compare.title': 'Hasonlítsd össze a három modellt',
    'compare.lead': 'Pontról pontra — hogy biztosan a legjobbat válaszd az üzletedhez.',
    'compare.row1': 'NFC fizetés',
    'compare.row2': 'Chip + PIN',
    'compare.row3': 'Android OS',
    'compare.row4': 'Saját app telepítés',
    'compare.row5': 'Nyomtató (beépített)',
    'compare.row6': 'Akkumulátor (mAh)',
    'compare.row7': 'Súly',
    'compare.row8': 'Ajánlott napi tranzakció',

    'term.fee.title': '0,65% jutalék — és kész.',
    'term.fee.lead': 'Nincs havidíj, nincs setup költség, nincs hűségidő. A SumUp-nál olcsóbb, a banki POS-nál egyszerűbb.',
    'term.fee.note': 'Az ár tartalmazza: hardver, magyar nyelvű setup, helyszíni betanítás, 12 hónap garancia, 24/7 support.',

    /* Kassza page */
    'kassza.eyebrow': '02 — Kassza rendszer',
    'kassza.h1_a': 'NAV-megfelelő kassza,',
    'kassza.h1_b': '30 perces betanítás.',
    'kassza.lead': 'A Festisale szoftver + NewLand kassza hardver = teljes körű megoldás. Készletkezelés, riportok, online számla — egy felületen.',

    'kassza.feats.title': 'Hat dolog, ami a napodat egyszerűbbé teszi.',
    'kassza.feats.f1.t': 'NAV-megfelelő',
    'kassza.feats.f1.p': 'Hivatalos adóügyi kassza, automatikus online adatszolgáltatás. Soha többet kézi jelentés.',
    'kassza.feats.f2.t': 'Készletkezelés',
    'kassza.feats.f2.p': 'Vonalkód-scan, raktárkészlet valós időben, alacsony készlet riasztás, beszállítói rendelések.',
    'kassza.feats.f3.t': 'Részletes riportok',
    'kassza.feats.f3.p': 'Napi zárás, kategória-bontás, top termékek, csúcsidőszakok — exportálható Excelbe.',
    'kassza.feats.f4.t': 'Minden fizetési mód',
    'kassza.feats.f4.p': 'Kártya, készpénz, SZÉP-kártya, utalvány, QR-kód — egy felületen kezelve.',
    'kassza.feats.f5.t': 'Online számlázás',
    'kassza.feats.f5.p': 'Számla, nyugta, áfás bizonylat — emailben kiküldve, NAV-hoz továbbítva.',
    'kassza.feats.f6.t': 'Könnyű betanítás',
    'kassza.feats.f6.p': 'Magyar nyelvű videók, helyszíni oktatás, 30 perces alap betanítás új kollégának.',

    'kassza.x800.tag': 'Smart ECR · dual display',
    'kassza.x800.title': 'NewLand X800',
    'kassza.x800.sub': 'Compact. Smart. Engaging. 8" merchant + 5" customer kijelző, beépített nyomtató és scanner. Egy szuper-kompakt all-in-one egység a pulton.',
    'kassza.x800.f1': '8" + 5" dual display',
    'kassza.x800.f2': 'Beépített hőnyomtató',
    'kassza.x800.f3': 'Vonalkód-olvasó',
    'kassza.x800.f4': 'Festisale natív integráció',

    'kassza.s90.tag': 'Prémium portable',
    'kassza.s90.title': 'NewLand S90 Dual',
    'kassza.s90.sub': 'Beyond Payment. 6,75" érintőképernyő, dual display, 3500 mAh akku — ha nem akarsz pultot, ez a teljes kassza a kezedben.',
    'kassza.s90.f1': '6,75" érintőkijelző',
    'kassza.s90.f2': '64+ óra üzemidő',
    'kassza.s90.f3': '2300+ tranzakció / töltés',
    'kassza.s90.f4': '20 mm slim profil',

    'kassza.steps.title': 'A bevezetés négy lépésben.',
    'kassza.steps.lead': '5 munkanap alatt élesítjük — a megrendeléstől az első valódi vásárlóig.',
    'kassza.steps.s1.t': 'Terminál szállítás',
    'kassza.steps.s1.p': 'A hardver 2 munkanap alatt megérkezik. Szükség esetén időpontot egyeztetünk.',
    'kassza.steps.s2.t': 'NAV regisztráció',
    'kassza.steps.s2.p': 'Mi intézzük az adóhatósági ügyintézést — neked csak egy aláírás kell.',
    'kassza.steps.s3.t': 'Helyszíni betanítás',
    'kassza.steps.s3.p': 'Kollégánk a helyszínen mutatja meg a rendszert — minden alkalmazottnak.',
    'kassza.steps.s4.t': 'Élesítés',
    'kassza.steps.s4.p': 'Az első valódi tranzakció előtt teszteljük — biztos, ami biztos.',

    'kassza.pricing.tag': 'Egységes ár',
    'kassza.pricing.title': '25 000 Ft / hó + 0,35% tranzakciós díj.',
    'kassza.pricing.lead': 'A szoftver, a NAV-szerviz, a support és a frissítések benne vannak. A hardver külön, egyszeri vétel.',

    /* Pricing page */
    'arak.eyebrow': '03 — Árazás',
    'arak.h1_a': 'Két út.',
    'arak.h1_b': 'Egyszerű árazás.',
    'arak.lead': 'Nincs rejtett költség, nincs hűségidő. Válaszd ki, ami az üzletedhez illik — és skálázz amikor készen állsz.',

    'arak.standalone.t': 'Önálló terminál',
    'arak.standalone.sub': 'Csak kártyaelfogadás — havidíj nélkül.',
    'arak.standalone.per': 'tranzakcióra',
    'arak.standalone.l1': 'Nincs havidíj — soha',
    'arak.standalone.l2': 'NewLand S30, N750 vagy N950S',
    'arak.standalone.l3': 'NFC + chip + mágnessáv',
    'arak.standalone.l4': '24/7 magyar support',
    'arak.standalone.l5': 'Bankfüggetlen',
    'arak.standalone.l6': '12 hónap garancia',

    'arak.kassza.t': 'Kassza rendszer',
    'arak.kassza.sub': 'Festisale szoftver + NewLand hardver.',
    'arak.kassza.per': '+ havidíj',
    'arak.kassza.l1': 'Festisale szoftver licensz',
    'arak.kassza.l2': 'NAV-megfelelő kassza',
    'arak.kassza.l3': 'Készletkezelés + riportok',
    'arak.kassza.l4': 'Online számlázás',
    'arak.kassza.l5': '0,35% tranzakciós díj',
    'arak.kassza.l6': 'Helyszíni betanítás + frissítések',
    'arak.kassza.badge': '⭐ Legjobb érték',

    'compare.title2': 'Hasonlítsd össze tételesen.',
    'arak.compare.fee': 'Tranzakciós díj',
    'arak.compare.monthly': 'Havidíj',
    'arak.compare.setup': 'Setup költség',
    'arak.compare.nav': 'NAV adóügyi kassza',
    'arak.compare.inv': 'Online számlázás',
    'arak.compare.inv_t': 'Készletkezelés',
    'arak.compare.report': 'Riportok',
    'arak.compare.support': 'Magyar support',

    'calc.title': 'Számítsd ki, melyik éri meg neked.',
    'calc.lead': 'Állítsd be a forgalmadat és nézd meg, mennyivel jönnél jobban ki az egyik vagy másik modellel.',
    'calc.turnover': 'Havi forgalom',
    'calc.segment': 'Mit forgalmazol?',
    'calc.seg1': 'Vendéglátás',
    'calc.seg2': 'Kiskereskedelem',
    'calc.seg3': 'Szolgáltatás',
    'calc.r1.t': 'Önálló terminál',
    'calc.r2.t': 'Kassza rendszer',
    'calc.cost': 'Havi költség',
    'calc.note': 'Az eredmény tájékoztató jellegű, a valós ajánlatot egyedi kalkuláció alapján adjuk.',

    'hw.title': 'Hardver árak — egyszeri vétel.',
    'hw.col1': 'Modell',
    'hw.col2': 'Típus',
    'hw.col3': 'Ár',

    /* Contact */
    'contact.eyebrow': '04 — Kapcsolat',
    'contact.h1_a': 'Beszéljünk az üzletedről.',
    'contact.h1_b': '',
    'contact.lead': 'Töltsd ki az űrlapot, vagy hívj minket — egy munkanap alatt visszajelzünk testreszabott ajánlattal.',
    'form.name': 'Teljes név',
    'form.company': 'Cég neve',
    'form.email': 'E-mail',
    'form.phone': 'Telefon',
    'form.segment': 'Szegmens',
    'form.segment_ph': 'Válaszd ki...',
    'form.product': 'Érdeklő termék',
    'form.product_ph': 'Bármi érdekel',
    'form.message': 'Megjegyzés',
    'form.message_ph': 'Pár szó az üzletről, jelenlegi rendszerről, igényekről...',
    'form.submit': 'Ajánlatot kérek',
    'form.success.t': 'Köszönjük!',
    'form.success.p': 'Egy munkanap alatt visszajelzünk a megadott e-mail címen.',

    'contact.info.t': 'Elérhetőségek',
    'contact.info.phone': 'Telefon',
    'contact.info.email': 'E-mail',
    'contact.info.hours': 'Nyitvatartás',
    'contact.info.hours_val': 'H–P: 8–18 · Sz: 10–14',
    'contact.info.address': 'Iroda',
    'contact.info.address_val': '1054 Budapest, Báthory u. 12.',

    'promise.t': 'Az ígéretünk',
    'promise.p1': '1 munkanapon belül visszajelzés',
    'promise.p2': 'Helyszíni bemutató díjmentesen',
    'promise.p3': 'Nincs rejtett költség, nincs hűségidő',
    'promise.p4': '24/7 magyar nyelvű support',
  },

  en: {
    'nav.products': 'Products',
    'nav.standalone': 'Standalone Terminals',
    'nav.standalone_sub': 'NewLand S30 · N750 · N950S',
    'nav.kassza': 'Cashier System',
    'nav.kassza_sub': 'Festisale + X800 · S90',
    'nav.pricing': 'Pricing',
    'nav.contact': 'Contact',
    'nav.cta': 'Get a quote',

    'cta.quote': 'Get a quote',
    'cta.products': 'Our products',
    'cta.learn_more': 'Learn more',
    'cta.demo': 'Book a demo',
    'cta.start': 'Start now',

    'home.tag': 'Available in Hungary — bank-independent solution',
    'home.h1_a': 'Payment made',
    'home.h1_b': 'simple.',
    'home.lead': 'Accept card payments with modern NewLand terminals — standalone or as a complete cashier system. No monthly fee, no bank switching.',
    'home.meta.merchants': 'merchants',
    'home.meta.uptime': 'transaction uptime',
    'home.meta.activation': 'Activation',
    'home.meta.activation_val': 'in 48h',

    'marquee.1': '400,000+ SMBs in Hungary',
    'marquee.2': '60%+ transactions already digital',
    'marquee.3': '18% yearly card payment growth',
    'marquee.4': 'Bank-independent solution',
    'marquee.5': 'NAV-compliant cashier',
    'marquee.6': 'Hungarian on-site support',

    'paths.eyebrow': 'Two paths, one goal',
    'paths.title': 'Choose what fits your business.',
    'paths.lead': 'Whether you just need card acceptance or a full point-of-sale — both come with premium NewLand hardware and Hungarian support.',
    'paths.standalone_tag': 'Standalone terminals',
    'paths.standalone_t': 'Card acceptance only',
    'paths.standalone_p': 'From portable mini POS to SmartPOS — 3 NewLand models, all 0.65% per transaction, no monthly fee.',
    'paths.kassza_tag': 'Cashier system',
    'paths.kassza_t': 'Festisale + hardware',
    'paths.kassza_p': 'NAV-compliant cashier software, inventory and integrated card acceptance. 25,000 HUF/mo + 0.35%.',

    'seg.eyebrow': 'Who it’s for',
    'seg.title': 'Any business — at any size.',
    'seg.lead': 'FESTIPAY runs across 12+ industries. A few typical cases:',
    'seg.retail.t': 'Retail',
    'seg.retail.p': 'Grocery, boutique, specialty shop — quick NFC payment at the counter.',
    'seg.retail.m': '120,000+ potential shops',
    'seg.hospo.t': 'Hospitality',
    'seg.hospo.p': 'Café, restaurant, bar — portable terminal at every table.',
    'seg.hospo.m': '45,000+ venues',
    'seg.mobile.t': 'Mobile / stand',
    'seg.mobile.p': 'Market, fair, food truck — battery, 4G, compact size.',
    'seg.mobile.m': '20,000+ mobile sellers',
    'seg.service.t': 'Services',
    'seg.service.p': 'Taxi, courier, salon — easy setup, NAV ready.',
    'seg.service.m': '60,000+ service providers',

    'feats.eyebrow': 'Why FESTIPAY',
    'feats.title': 'Six reasons 400,000+ SMBs already switched.',
    'feats.f1.t': 'Bank-independent',
    'feats.f1.p': 'No need to switch banks — it connects to your existing account. Your money stays where it always did.',
    'feats.f2.t': 'No monthly fee',
    'feats.f2.p': 'Pay only on turnover: 0.65% per transaction. No setup fee, no lock-in.',
    'feats.f3.t': 'NAV-compliant',
    'feats.f3.p': 'The Festisale software is an official NAV cashier — automatic daily close, online tax data submission.',
    'feats.f4.t': 'Live in 48 hours',
    'feats.f4.p': 'From quote to first transaction in 2 business days. On-site training, Hungarian manual.',
    'feats.f5.t': 'Hungarian support',
    'feats.f5.p': 'Phone, email, live chat. On-site service in Budapest and 12 major cities.',
    'feats.f6.t': 'Modern hardware',
    'feats.f6.p': 'NewLand premium terminals — NFC, touchscreen, long battery life, industrial-grade durability.',

    'testi.eyebrow': 'What they say',
    'testi.title': 'Hungarian merchants, real experiences.',
    'testi.1.q': 'It paid for itself in two weeks — 70% of our café revenue is on cards, and the no-monthly-fee model is a huge advantage.',
    'testi.1.n': 'E. Kovács',
    'testi.1.r': 'Sigil Café · Budapest',
    'testi.2.q': 'NAV close runs by itself, training took 30 minutes. My two colleagues picked up Festisale immediately.',
    'testi.2.n': 'P. Nagy',
    'testi.2.r': 'Tulipán Bakery · Debrecen',
    'testi.3.q': 'I use the S30 24/7 in the taxi and it has never let me down. NFC payment is ~0.3 seconds, customers love it.',
    'testi.3.n': 'T. Varga',
    'testi.3.r': 'Mobile taxi service',

    'finalcta.eyebrow': 'Ready?',
    'finalcta.title': 'Start accepting card payments — this week.',
    'finalcta.lead': 'Send a quote request or call us — our team responds within 1 business day with a tailored plan.',
    'finalcta.btn_demo': 'Book a demo',
    'finalcta.btn_call': 'Call: +36 1 555 0100',

    'footer.tagline': 'Modern, bank-independent card acceptance for Hungarian merchants. One brand, two paths: standalone terminal or full cashier system.',
    'footer.products': 'Products',
    'footer.company': 'Company',
    'footer.support': 'Support',
    'footer.about': 'About',
    'footer.partners': 'Partners',
    'footer.careers': 'Careers',
    'footer.help': 'Help center',
    'footer.docs': 'Documents',
    'footer.status': 'System status',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.copy': '© 2026 FESTIPAY — All rights reserved.',

    'term.eyebrow': '01 — Standalone terminals',
    'term.h1_a': 'Card acceptance',
    'term.h1_b': 'with no monthly fee.',
    'term.lead': 'Three NewLand models, one offer: 0.65% per transaction, no hidden costs.',

    'term.s30.tag': 'miniPOS · entry',
    'term.s30.title': 'NewLand S30',
    'term.s30.sub': 'Slim. Smart. Sleek. Our smallest and lightest terminal — 138 grams, 16.5 mm thick. Perfect when you need mobility or counter space is tight.',
    'term.s30.f1': 'NFC + Chip + Magstripe',
    'term.s30.f2': '0.3s payment time',
    'term.s30.f3': 'PCI 7.x security',
    'term.s30.f4': 'WiFi + 4G',

    'term.n750.tag': 'Android miniPOS',
    'term.n750.title': 'NewLand N750',
    'term.n750.sub': 'Compact. Connected. Confident. 5.5" touchscreen on Android — run your own apps, advanced transaction log, loyalty program integration.',
    'term.n750.f1': 'Android 12 OS',
    'term.n750.f2': '5.5" HD display',
    'term.n750.f3': '4G + WiFi + BT',
    'term.n750.f4': 'App support',

    'term.n950s.tag': 'SmartPOS · premium',
    'term.n950s.title': 'NewLand N950S',
    'term.n950s.sub': 'Premium. Powerful. Portable. Octa-core Android, 3500 mAh battery, high brightness. For 200+ transactions a day, this is the top model.',
    'term.n950s.f1': '3500 mAh battery',
    'term.n950s.f2': 'Octa-core CPU',
    'term.n950s.f3': '2300+ transactions / charge',
    'term.n950s.f4': 'Industrial durability',

    'term.spec.hw': 'Hardware price',
    'term.spec.fee': 'Transaction fee',
    'term.spec.use': 'Best for',
    'term.s30.use': 'Mobile, taxi, courier, food truck',
    'term.n750.use': 'Shop, café, reception',
    'term.n950s.use': 'Restaurant, premium retail, high traffic',

    'compare.title': 'Compare all three models',
    'compare.lead': 'Side by side — so you pick exactly what your business needs.',
    'compare.row1': 'NFC payment',
    'compare.row2': 'Chip + PIN',
    'compare.row3': 'Android OS',
    'compare.row4': 'Install your own apps',
    'compare.row5': 'Built-in printer',
    'compare.row6': 'Battery (mAh)',
    'compare.row7': 'Weight',
    'compare.row8': 'Recommended daily transactions',

    'term.fee.title': '0.65% transaction fee — that’s it.',
    'term.fee.lead': 'No monthly fee, no setup cost, no lock-in. Cheaper than SumUp, simpler than a bank POS.',
    'term.fee.note': 'Price includes: hardware, Hungarian setup, on-site training, 12-month warranty, 24/7 support.',

    'kassza.eyebrow': '02 — Cashier system',
    'kassza.h1_a': 'NAV-compliant cashier,',
    'kassza.h1_b': '30-minute training.',
    'kassza.lead': 'Festisale software + NewLand cashier hardware = a complete solution. Inventory, reports, online invoicing — in one interface.',

    'kassza.feats.title': 'Six things that make your day simpler.',
    'kassza.feats.f1.t': 'NAV-compliant',
    'kassza.feats.f1.p': 'Official cashier, automatic online tax data submission. Never file by hand again.',
    'kassza.feats.f2.t': 'Inventory',
    'kassza.feats.f2.p': 'Barcode scan, real-time stock, low-stock alerts, supplier ordering.',
    'kassza.feats.f3.t': 'Detailed reports',
    'kassza.feats.f3.p': 'Daily close, category breakdowns, top products, peak hours — exportable to Excel.',
    'kassza.feats.f4.t': 'Every payment method',
    'kassza.feats.f4.p': 'Card, cash, SZÉP card, voucher, QR code — handled in one interface.',
    'kassza.feats.f5.t': 'Online invoicing',
    'kassza.feats.f5.p': 'Invoice, receipt, VAT document — sent by email, forwarded to NAV.',
    'kassza.feats.f6.t': 'Easy training',
    'kassza.feats.f6.p': 'Hungarian videos, on-site training, 30-minute basic training for new staff.',

    'kassza.x800.tag': 'Smart ECR · dual display',
    'kassza.x800.title': 'NewLand X800',
    'kassza.x800.sub': 'Compact. Smart. Engaging. 8" merchant + 5" customer display, built-in printer and scanner. One ultra-compact all-in-one unit on the counter.',
    'kassza.x800.f1': '8" + 5" dual display',
    'kassza.x800.f2': 'Built-in thermal printer',
    'kassza.x800.f3': 'Barcode scanner',
    'kassza.x800.f4': 'Native Festisale integration',

    'kassza.s90.tag': 'Premium portable',
    'kassza.s90.title': 'NewLand S90 Dual',
    'kassza.s90.sub': 'Beyond Payment. 6.75" touchscreen, dual display, 3500 mAh — if you don’t want a counter, this is the full cashier in your hand.',
    'kassza.s90.f1': '6.75" touchscreen',
    'kassza.s90.f2': '64+ hours runtime',
    'kassza.s90.f3': '2300+ tx / charge',
    'kassza.s90.f4': '20 mm slim profile',

    'kassza.steps.title': 'Rollout in four steps.',
    'kassza.steps.lead': 'Live in 5 business days — from order to first real customer.',
    'kassza.steps.s1.t': 'Terminal delivery',
    'kassza.steps.s1.p': 'Hardware arrives in 2 business days. Appointment if needed.',
    'kassza.steps.s2.t': 'NAV registration',
    'kassza.steps.s2.p': 'We handle the tax authority paperwork — you just sign.',
    'kassza.steps.s3.t': 'On-site training',
    'kassza.steps.s3.p': 'Our colleague shows you the system on-site — for every staff member.',
    'kassza.steps.s4.t': 'Go live',
    'kassza.steps.s4.p': 'We test before the first real transaction — better safe than sorry.',

    'kassza.pricing.tag': 'One simple price',
    'kassza.pricing.title': '25,000 HUF/month + 0.35% transaction fee.',
    'kassza.pricing.lead': 'Software, NAV service, support and updates are included. Hardware is a separate one-time purchase.',

    'arak.eyebrow': '03 — Pricing',
    'arak.h1_a': 'Two paths.',
    'arak.h1_b': 'Simple pricing.',
    'arak.lead': 'No hidden costs, no lock-in. Pick what fits your business — and scale when you’re ready.',

    'arak.standalone.t': 'Standalone terminal',
    'arak.standalone.sub': 'Card acceptance only — no monthly fee.',
    'arak.standalone.per': 'per transaction',
    'arak.standalone.l1': 'No monthly fee — ever',
    'arak.standalone.l2': 'NewLand S30, N750 or N950S',
    'arak.standalone.l3': 'NFC + chip + magstripe',
    'arak.standalone.l4': '24/7 Hungarian support',
    'arak.standalone.l5': 'Bank-independent',
    'arak.standalone.l6': '12-month warranty',

    'arak.kassza.t': 'Cashier system',
    'arak.kassza.sub': 'Festisale software + NewLand hardware.',
    'arak.kassza.per': '+ monthly fee',
    'arak.kassza.l1': 'Festisale software license',
    'arak.kassza.l2': 'NAV-compliant cashier',
    'arak.kassza.l3': 'Inventory + reports',
    'arak.kassza.l4': 'Online invoicing',
    'arak.kassza.l5': '0.35% transaction fee',
    'arak.kassza.l6': 'On-site training + updates',
    'arak.kassza.badge': '⭐ Best value',

    'compare.title2': 'Compare line by line.',
    'arak.compare.fee': 'Transaction fee',
    'arak.compare.monthly': 'Monthly fee',
    'arak.compare.setup': 'Setup cost',
    'arak.compare.nav': 'NAV cashier',
    'arak.compare.inv': 'Online invoicing',
    'arak.compare.inv_t': 'Inventory',
    'arak.compare.report': 'Reports',
    'arak.compare.support': 'Hungarian support',

    'calc.title': 'See which model is best for you.',
    'calc.lead': 'Set your turnover and see how much you’d pay with each model.',
    'calc.turnover': 'Monthly turnover',
    'calc.segment': 'What do you sell?',
    'calc.seg1': 'Hospitality',
    'calc.seg2': 'Retail',
    'calc.seg3': 'Services',
    'calc.r1.t': 'Standalone terminal',
    'calc.r2.t': 'Cashier system',
    'calc.cost': 'Monthly cost',
    'calc.note': 'Result is indicative; the actual offer is based on a custom calculation.',

    'hw.title': 'Hardware prices — one-time purchase.',
    'hw.col1': 'Model',
    'hw.col2': 'Type',
    'hw.col3': 'Price',

    'contact.eyebrow': '04 — Contact',
    'contact.h1_a': 'Let’s talk about your business.',
    'contact.h1_b': '',
    'contact.lead': 'Fill out the form or call us — we respond within 1 business day with a custom offer.',
    'form.name': 'Full name',
    'form.company': 'Company name',
    'form.email': 'Email',
    'form.phone': 'Phone',
    'form.segment': 'Segment',
    'form.segment_ph': 'Choose...',
    'form.product': 'Product of interest',
    'form.product_ph': 'Anything works',
    'form.message': 'Message',
    'form.message_ph': 'A few words about your business, current setup, needs...',
    'form.submit': 'Request a quote',
    'form.success.t': 'Thank you!',
    'form.success.p': 'We’ll get back to you within 1 business day at the email you provided.',

    'contact.info.t': 'Contact details',
    'contact.info.phone': 'Phone',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Hours',
    'contact.info.hours_val': 'Mon–Fri: 8–18 · Sat: 10–14',
    'contact.info.address': 'Office',
    'contact.info.address_val': 'Báthory u. 12, 1054 Budapest',

    'promise.t': 'Our promise',
    'promise.p1': 'Response within 1 business day',
    'promise.p2': 'Free on-site demo',
    'promise.p3': 'No hidden cost, no lock-in',
    'promise.p4': '24/7 Hungarian support',
  }
};

const LangManager = {
  current: 'hu',
  init() {
    this.current = localStorage.getItem('festisale_lang') || 'hu';
    this.apply(this.current);
    this.bindToggle();
  },
  apply(lang) {
    if (!I18N[lang]) lang = 'hu';
    this.current = lang;
    document.documentElement.lang = lang;
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      const val = I18N[lang][key];
      if (val !== undefined) el.textContent = val;
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
      const key = el.getAttribute('data-i18n-placeholder');
      const val = I18N[lang][key];
      if (val !== undefined) el.setAttribute('placeholder', val);
    });
    document.querySelectorAll('.lang-btn').forEach(btn => {
      btn.classList.toggle('active', btn.dataset.lang === lang);
    });
    localStorage.setItem('festisale_lang', lang);
  },
  bindToggle() {
    document.querySelectorAll('.lang-btn').forEach(btn => {
      btn.addEventListener('click', () => this.apply(btn.dataset.lang));
    });
  }
};

document.addEventListener('DOMContentLoaded', () => LangManager.init());
